# File: .github/workflows/azure_infra.yml

on: 
  workflow_dispatch:

name: infra

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az appservice plan create -g ${{ secrets.rg }} -n ${{ secrets.asp }} --is-linux --number-of-workers 1 --sku B1
          az webapp create -g ${{ secrets.rg }} -p ${{ secrets.asp }} -n ${{ secrets.webapp }}  --runtime "node|10.14"
          az extension add -n application-insights
          locName=`az group show --name ${{ secrets.rg }} --query location --output tsv`
          az monitor app-insights component create --app apimon${{ secrets.webapp }} --location $locName --kind web -g ${{ secrets.rg }} --application-type web --retention-time 30
          instrumentationKey=`az monitor app-insights component show --app apimon${{ secrets.webapp }} --resource-group ${{ secrets.rg }} --query  "instrumentationKey" --output tsv`
          az webapp config appsettings set --name $webapp --resource-group ${{ secrets.rg }} --settings APPINSIGHTS_INSTRUMENTATIONKEY=$instrumentationKey APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=$instrumentationKey ApplicationInsightsAgent_EXTENSION_VERSION=~2




